package(default_visibility = ["//visibility:public"])

filegroup(
    name = "wav_params",
    srcs = [
        "wav_params.txt",
    ],
)

filegroup(
    name = "encoder_params",
    srcs = [
        "encoder_params.txt",
    ],
)
