package(default_visibility = ["//visibility:public"])

filegroup(
    name = "easy",
    srcs = [
        "easy.wav",
        "easy_encoder_params.txt",
    ],
)

filegroup(
    name = "medium",
    srcs = [
        "medium.wav",
        "medium_encoder_params.txt",
    ],
)
