package(default_visibility = ["//visibility:public"])

filegroup(
    name = "encoded_and_resampled_audio",
    srcs = [
        "encoded_and_resampled_audio.wav",
    ],
)

filegroup(
    name = "encoded_and_resampled_audio_encoder_params",
    srcs = [
        "encoded_and_resampled_audio_encoder_params.txt",
    ],
)
