package(default_visibility = ["//visibility:public"])

cc_library(
    name = "encoder_base",
    srcs = ["encoder_base.cc"],
    hdrs = ["encoder_base.h"],
    deps = [
        "//src/common/interface/proto:cc_encoder_params_proto",
        "@com_google_glog//:glog",
    ],
)
