package(default_visibility = ["//visibility:public"])

cc_library(
    name = "math_utils",
    srcs = ["math_utils.cpp"],
    hdrs = ["math_utils.h"],
    deps = [
        "@com_google_glog//:glog",
    ],
)
