package(default_visibility = ["//visibility:public"])

cc_library(
    name = "google_test_main",
    testonly = 1,
    srcs = ["google_test_main.cpp"],
    deps = [
        "@com_google_glog//:glog",
        "@com_google_googletest//:gtest",
    ],
    alwayslink = 1,
)
