name: clear-cache

on:
  schedule:
    - cron: '48 7 * * *'

jobs:
  clear:

    runs-on: ubuntu-latest

    steps:  
    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Clean
      run: |
        rm -rf "/home/runner/.cache/bazel/*"
