name: unit-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '48 19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_FOLDER: /home/runner/tmp/africamonkey

    steps:  
    - uses: actions/checkout@v1

    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.16.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Set Environment Variables
      run: |
        export TEST_FOLDER=$TEST_FOLDER

    - name: Build
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build --disk_cache="/home/runner/.cache/bazel/fastbuild" //...

    - name: Test
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test --disk_cache="/home/runner/.cache/bazel/fastbuild" --test_output errors //...

    - name: ASAN Build
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build --config=asan --disk_cache="/home/runner/.cache/bazel/asan" //...

    - name: ASAN Test
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test --config=asan --disk_cache="/home/runner/.cache/bazel/asan" --test_output errors //...
